mapping_drogerie  = {
    "tiernahrung": "Tiere",
    "hundefutter": "Tiere",
    "katzenfutter": "Tiere",
    "haustierbedarf": "Tiere",
    "tierzubehör": "Tiere",
    "haustierpflege": "Tiere",
    "tiermedizin": "Tiere",
    "tierkäfige": "Tiere",
    "vogelkäfig": "Tiere",
    "nagerfutter": "Tiere",
    "parfum": "Parfum",
    "parfümflasche": "Parfum",
    "damendüfte": "Parfum",
    "herrendüfte": "Parfum",
    "duft": "Parfum",
    "eau de": "Parfum",
    "makeup": "Makeup",
    "puder": "Makeup",
    "highlighter": "Makeup",
    "blush": "Makeup",
    "lidschadden": "Makeup",
    "kajal": "Makeup",
    "lippenstift": "Makeup",
    "mascara": "Makeup",
    "foundation": "Makeup",
    "rouge": "Makeup",
    "babywindeln": "Baby",
    "windel": "Baby",
    "wickeltasche": "Baby",
    "baby": "Baby",

    "babyöl": "Baby",
    "babybrei": "Baby",
    "babyspielzeug": "Baby",
    "babymode": "Baby",
    "lebensmittel": "Lebensmittel und Ernährung",
    "lebensmittelgeschäft": "Lebensmittel und Ernährung",
    "biolebensmittel": "Lebensmittel und Ernährung",
    "frischeprodukte": "Lebensmittel und Ernährung",
    "veganeprodukte": "Lebensmittel und Ernährung",
    "hygieneprodukte": "Hygiene",
    "toilettenpapier": "Hygiene",
    "handdesinfektionsmittel": "Hygiene",
    "seife": "Hygiene",
    "gesichtsmasken": "Hygiene",
    "deo": "Hygiene",
    "rasierer": "Hygiene",
    "shampoo": "Hygiene",
    "zahn": "Hygiene",
    "dusch": "Hygiene",
    "fotokameras": "Foto",
    "fotografieausrüstung": "Foto",
    "kameraobjektive": "Foto",
    "fotostudio": "Foto",
    "gesundheit": "Gesundheit",
    "vitamine": "Gesundheit",
    "schnupfen": "Gesundheit",
    "durchfall": "Gesundheit",
    "husten": "Gesundheit",
    "grippe": "Gesundheit",
    "magen": "Gesundheit",
    "fieber": "Gesundheit",
    "pflaster": "Gesundheit",
    "schmerzmittel": "Gesundheit",
    "nahrungsergänzungsmittel": "Gesundheit",
    "medizinprodukte": "Gesundheit",
     "apfel" : "Obst",
    "äpfel" : "Obst",
    "banane" : "Obst",
    "birne" : "Obst",
    "avocado" : "Obst",
    "erdbeere" : "Obst",
    "orange" : "Obst",
    "traube" : "Obst",
    "kirsche" : "Obst",
    "beeren" : "Obst",
    "ananas" : "Obst",
    "mango" : "Obst",
    "melone" : "Obst",
    "limette" : "Obst",
    "zitrone" : "Obst",
    "pfirsich" : "Obst",
    "gurke" : "Gemüse",
    "zwiebel" : "Gemüse",
    "tomate" : "Gemüse",
    "kartoffel" : "Gemüse",
    "karotte" : "Gemüse",
    "kohl" : "Gemüse",
    "pilz" : "Gemüse",
    "erbse" : "Gemüse",
    "spinat" : "Gemüse",
    "brokkoli" : "Gemüse",
    "salat" : "Gemüse",
    "quark" : "Molkerei",
    "butter" : "Molkerei",
    "joghurt" : "Molkerei",
    "käse" : "Molkerei",
    "rahm" : "Molkerei",
    "sahne": "Molkerei",
    "oberst": "Molkerei",
    "eier" : "Food",
    "nudel" : "Food",
    "mehl": "Food",
    "öl" : "Food",
    "nutella" : "Food",
    "marmelade" : "Food",
    "honig" : "Food",
    "sosse" : "Food",
    "soße" : "Food",
    "brot" : "Food",
    "bröt" : "Food",
    "zucker" : "Food",
    "gewürz" : "Food",
    "konserv" : "Food",
    "papier" : "Non-Food",
    "parfum" : "Non-Food",
    "spül" : "Non-Food",
    "schnitzel" : "Fleisch",
    "brust" : "Fleisch",
    "kotelett" : "Fleisch",
    "steak" : "Fleisch",
    "schenkel" : "Fleisch",
    "speck" : "Fleisch",
    "wurst" : "Fleisch",
    "würst" : "Fleisch",
    "schinken" : "Fleisch",
    "salami" : "Fleisch",
    "wiener" : "Fleisch",
    "bauch" : "Fleisch",
    "fleisch" : "Fleisch",
    "hühnchen" : "Fleisch",
    "hähnchen" : "Fleisch",
    "huhn" : "Fleisch",
    "fisch" : "Fleisch",
    "lachs": "Fleisch",
    "hering": "Fleisch",
    "thunfisch": "Fleisch",
    "makrele": "Fleisch",
    "forelle": "Fleisch",
    "schokolade" : "Snacks",
    "gummibären" : "Snacks",
    "jumpys" : "Snacks",
    "chips" : "Snacks",
    "salzstangen" : "Snacks",
    "keks" : "Snacks",
    "flake" : "Snacks",
    "snack" : "Snacks",
    "pflanz" : "Pflanzen",
    "orchide" : "Pflanzen",
    "kaktus": "Pflanzen",
    "fanta" : "Getränke",
    "cola" : "Getränke",
    "saft" : "Getränke",
    "limonade" : "Getränke",
    "tee" : "Getränke",
    "wasser" : "Getränke",
    "shake" : "Getränke",
    "schorle" : "Getränke",
    "energy" : "Getränke",
    "getränk" : "Getränke",
    "bier" : "Getränke",
    "wodka" : "Getränke",
    "schnaps" : "Getränke",
    "likör" : "Getränke",
    "weinbr" : "Getränke"
}
